### ISSUE TITLE
Jitter on some elements

### ISSUE THREAD

**Issue by BenHerbst** [Armanebtekari/my-site#2]
One some elements is a jitter in your website

**Comment by Armanebtekari** [comment]
Which Element?

**Comment by BenHerbst** [comment]
![grafik](https://user-images.githubusercontent.com/83538916/188239001-454aa3ce-dec8-4332-849c-ba131df4d22e.png)
this component, I use Firefox and Pop!_OS 22.04

**Comment by BenHerbst** [comment]
![grafik](https://user-images.githubusercontent.com/83538916/188239097-25f212d4-c211-4f69-b63d-4e39417fd880.png)
the top left , this elements all look same actually, but one is broken
